### PR TITLE
[YUNIKORN-956] remove old REST handlers: objects and code

### PR DESCRIPTION
**Pull request by cchung100m**
### What is this PR for?
Remove old REST API and its handlers.

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Documents might need to update

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-956

### How should this be tested?

make test

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by yangwwei — CHANGES_REQUESTED** [review]
Please hold on merging this until we figured out what is the correct way to do this. Please see my comments in https://issues.apache.org/jira/browse/YUNIKORN-954.

**Comment by cchung100m** [comment]
Hi @yangwwei 

Thanks for the prompt reply and comments.

**Comment by craigcondit** [comment]
Hi @cchung100m, we are finally to the point where we are ready to remove the old v1 REST API. Are you able to update this PR and resolve the conflicts?

**Comment by craigcondit** [comment]
Closed in favor of #403 as this one has gone stale.

**Pull request closed without merging**
