### PR TITLE
[YUNIKORN-1912] Upgrade golang dependencies for CVEs

### PR DESCRIPTION
**Pull request by pegasas**
### What is this PR for?

golang.org/x/net: need to move to at least 0.13 due to CVEs

Should push all replace ones we use to latest:

	golang.org/x/crypto => golang.org/x/crypto v0.12.0
	golang.org/x/net => golang.org/x/net v0.14.0
	golang.org/x/sys => golang.org/x/sys v0.12.0
	golang.org/x/text => golang.org/x/text v0.13.0
	golang.org/x/tools => golang.org/x/tools v0.12.0

This needs to be checked against all repos

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [x] - Task

### What is the Jira issue?

https://issues.apache.org/jira/browse/YUNIKORN-1912

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — CHANGES_REQUESTED** [review]
This is the current latest version list (small diff with the PR)
```
	golang.org/x/crypto => golang.org/x/crypto v0.12.0
	golang.org/x/net => golang.org/x/net v0.14.0
	golang.org/x/sys => golang.org/x/sys v0.12.0
	golang.org/x/text => golang.org/x/text v0.13.0
	golang.org/x/tools => golang.org/x/tools v0.12.0
```
A new go release for CVE fixes is coming this week. We should check if that release includes any version updates to the libraries used.

**Comment by wilfred-s** [comment]
no new libs were released so the list is good

**Review by craigcondit — APPROVED** [review]
+1 LGTM.

**Review by wilfred-s — COMMENTED** [review]
LGTM +1

**Comment by pegasas** [comment]
Thanks!

**Pull request closed without merging**
