### PR TITLE
[YUNIKORN-2176] Add test for user & group max resource changes

### PR DESCRIPTION
**Pull request by manirajv06**
### What is this PR for?
Added test coverage to ensure max resource changes with different types, nil etc has been covered for user & groups.

### What type of PR is it?
* [ ] - Improvement

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2176

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by manirajv06** [comment]
@pbacsko @craigcondit @FrankYang0529 can you take a look?

**Comment by manirajv06** [comment]
@FrankYang0529 can you take a look?

**Comment by FrankYang0529** [comment]
> @FrankYang0529 can you take a look?

Yes, I'll review it today. Thanks.

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks.

**Pull request closed without merging**
