### PR TITLE
[YUNIKORN-2263] Initialize node attributes if it's nil

### PR DESCRIPTION
**Pull request by pegasas**
### What is this PR for?

This is a short addendum to [YUNIKORN-1124](https://issues.apache.org/jira/browse/YUNIKORN-1124): init `sn.attributes` if it's nil.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
[YUNIKORN-2263](https://issues.apache.org/jira/browse/YUNIKORN-2263)

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by pbacsko** [comment]
@pegasas this ticket is about something else. The "ready" flag a Node object is treated separately from the rest which comes from `NodeInfo.Attributes`. Your change makese sense but this is not YUNIKORN-1139.

To me, it looks like an addendum to YUNIKORN-1124, which was closed a long time ago. I suggest creating a new JIRA which refers to YUNIKORN-1124 and rename this PR.

**Review by pbacsko — CHANGES_REQUESTED** [review]
Pls create new ticket & update this PR as I requested.

**Comment by pegasas** [comment]
> Pls create new ticket & update this PR as I requested.

sure.

I will create another one.

**Comment by pbacsko** [comment]
@pegasas I created the JIRA and will merge this small change soon.

**Review by pbacsko — APPROVED** [review]
+1

**Pull request closed without merging**
