### PR TITLE
[YUNIKORN-1075]Upgrade Prometheus version

### PR DESCRIPTION
**Pull request by HuangTing-Yao**
### What is this PR for?
Upgrade the `prometheus/client_golang` version to 1.12.2 in `go.mod`

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1075

### How should this be tested?
prometheus_table
prometheus_graph
prometheus_target

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by wilfred-s** [comment]
@HuangTing-Yao is it possible to move to [1.13.1](https://github.com/prometheus/client_golang/releases/tag/v1.13.1) instead of 0.12.2? We're making a jump can we make it as big as possible. 1.14.0 seems a bit too new to use but the 1.13 release has had some time out already.

**Comment by HuangTing-Yao** [comment]
> @HuangTing-Yao is it possible to move to [1.13.1](https://github.com/prometheus/client_golang/releases/tag/v1.13.1) instead of 0.12.2? We're making a jump can we make it as big as possible. 1.14.0 seems a bit too new to use but the 1.13 release has had some time out already.

@wilfred-s  Sure, Let me give iti a try. I will try to upgrade prometheus client_go version to 1.13.1 to instead of 1.12.2.
Will commit soon.

**Comment by HuangTing-Yao** [comment]
@wilfred-s Already update to 1.13.1. Please take a look.

**Review by wilfred-s — APPROVED** [review]
LGTM

**Pull request closed without merging**
