### PR TITLE
[YUNIKORN-2089] Move usedResource type and tests to their own files

### PR DESCRIPTION
**Pull request by vinayakphegde**
### What is this PR for?
* Moved usedResource type and the related functions to their own files
* Created unit tests for usedResource functions

### What type of PR is it?
* [x] - Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2089

### CODE REVIEW

**Comment by pbacsko** [comment]
@vinayakphegde please resolve the merge conflict

**Comment by vinayakphegde** [comment]
> @vinayakphegde please resolve the merge conflict

Rebased it!! please check now!!

**Review by pbacsko — CHANGES_REQUESTED** [review]
1. Can we rename the file to tracked_resource.go to match the struct name?
2. I extended the JIRA ticket a bit, please implement the String() method.

**Comment by vinayakphegde** [comment]
> 1. Can we rename the file to tracked_resource.go to match the struct name?
> 2. I extended the JIRA ticket a bit, please implement the String() method.

Thanks for pointing it out. Made the requested changes

**Comment by pbacsko** [comment]
One more thing - please look for places where we log TrackedResource, we likely use zap.Any(). Replace that with zap.Stringer().

**Comment by vinayakphegde** [comment]
> One more thing - please look for places where we log TrackedResource, we likely use zap.Any(). Replace that with zap.Stringer().

Sure, will look into that.

**Comment by pbacsko** [comment]
@vinayakphegde any update on this?

**Pull request closed without merging**
