### PR TITLE
[YUNIKORN-1549][core] Introduce a config to specify what attribute to use as instance type

### PR DESCRIPTION
**Pull request by zhuqi-lucas**
### What is this PR for?
We add a new config in https://github.com/apache/yunikorn-k8shim/pull/518 , the core side will use the extraconfig.
And we need to parse the instanceType in core side.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [x] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1549
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by craigcondit** [comment]
Please add a constant to the SI for the configuration key and default value. There is NO need to change the shim at all - every configuration setting in the configmap is passed along to the core as of v1.2.0.

**Comment by wilfred-s** [comment]
-1 see the remarks in the K8shim PR.
First fix the attributes implementation and use a standardised label name.

**Comment by zhuqi-lucas** [comment]
Hi @wilfred-s ,@craigcondit , https://github.com/apache/yunikorn-k8shim/pull/519 has been merged, and i have changed the code now.

And i will add the default value settings to yunikorn-site after this merged.

**Comment by craigcondit** [comment]
@zhuqi-lucas, I'm now -1 on this approach. As I'm looking at this I see a problem. The core should not have any knowledge of the shim -- it is meant to be platform-agnostic, so we shouldn't have a Kubernetes-specific key or value present here. We already have an `InstanceType` constant in the SI that resolves to `si/instance-type`.  The kubernetes-specific code should go in the shim, and be used to determine which node label or annotation should be used to populate the `si/instance-type` attribute. This way, no matter what implementation the shim uses, the core can always rely on a node's instance type (if specified) being present in that attribute.

**Comment by zhuqi-lucas** [comment]
Thank you @craigcondit for review and clarify, i change the core side code to use the SI value:
'''
InstanceType        = "si/instance-type"
'''

And the shim side will fill this value, if i make sense right?

**Comment by craigcondit** [comment]
> Thank you @craigcondit for review and clarify, i change the core side code to use the SI value: InstanceType = "si/instance-type"
> 
> And the shim side will fill this value, if i make sense right?

Yes, the shim side code will need to be written yet, but this looks better.

**Review by craigcondit — APPROVED** [review]
+1, but would like @wilfred-s to weigh in as well.

**Comment by zhuqi-lucas** [comment]
Thank you @craigcondit for quick checking, and the shim side change i submitted a new PR:
https://github.com/apache/yunikorn-k8shim/pull/531

**Comment by yzhangal** [comment]
Thanks @craigcondit for approving the PR. HI @wilfred-s, would you please help reviewing again? thanks. FYI @zhuqi-lucas

**Pull request closed without merging**
