### PR TITLE
[YUNIKORN-2499] MockResponseWriter.write() should append new bytes instead of rewrite it

### PR DESCRIPTION
**Pull request by targetoee**
### What is this PR for?
In the previous case, the mock response writes data only once and works well.
However, if we want to support compression in the future, it may encounter issues because some compression writers (such as gzip writers) may need to write data multiple times.
This PR aims to fix it so that it can support more use cases.

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### What is the Jira issue?
[YUNIKORN-2499](https://issues.apache.org/jira/browse/YUNIKORN-2499)

### How should this be tested?
`make test`

### CODE REVIEW

**Comment by chia7712** [comment]
With this PR, `make test` could result in failed tests:
```sh
FAIL	github.com/apache/yunikorn-core/pkg/scheduler/tests	39.840s
ok  	github.com/apache/yunikorn-core/pkg/scheduler/ugm	1.036s	coverage: 92.9% of statements
ok  	github.com/apache/yunikorn-core/pkg/webservice	2.279s	coverage: 87.1% of statements
FAIL
make: *** [Makefile:207: test] Error 1
```

**Comment by chia7712** [comment]
I have filed https://issues.apache.org/jira/browse/YUNIKORN-2511 to trace that flaky

**Comment by targetoee** [comment]
I have rebased this branch to [YUNIKORN-2511](https://issues.apache.org/jira/browse/YUNIKORN-2511) locally and checked all test cases pass. It should work fine once YUNIKORN-2511 is resolved.

**Comment by chia7712** [comment]
> I have rebased this branch to YUNIKORN-2511 locally and checked all test cases pass. It should work fine once YUNIKORN-2511 is resolved.

Happy to know it 😃 

Let us fix YUNIKORN-2511 first, and then rebase code to check CI again before merging this PR

**Comment by chia7712** [comment]
@targetoee please rebase code for #827

**Comment by targetoee** [comment]
@chia7712 Done

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request closed without merging**
