### PR TITLE
[YUNIKORN-1983] Add config to statedump

### PR DESCRIPTION
**Pull request by brandboat**
### What is this PR for?
Add SchedulerConfig and extra configs in `/ws/v1/fullstatedump`

### What type of PR is it?
* [x] - Improvement

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1983

### How should this be tested?
covered by unit test

### Questions:
* [x] - It needs documentation => https://yunikorn.apache.org/docs/next/api/scheduler/#retrieve-full-state-dump need update after this pr merged, will open another jira/pr to fix this

### CODE REVIEW

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thanks.

**Comment by manirajv06** [comment]
@brandboat Now that #652 has gone in, can you rebase and apply changes on top of it?

**Comment by brandboat** [comment]
> @brandboat Now that https://github.com/apache/yunikorn-core/pull/652 has gone in, can you rebase and apply changes on top of it?

roger that

**Comment by brandboat** [comment]
gentle ping @FrankYang0529, @manirajv06 . Already rebased the latest commit and addressed comments. Could you take a look ? Many thanks !

**Review by manirajv06 — APPROVED** [review]

**Pull request closed without merging**
