### PR TITLE
[YUNIKORN-2169] Fix queue resource update through configmaps

### PR DESCRIPTION
**Pull request by manirajv06**
### What is this PR for?
Queue resource update should work for any changes as expected. For example, adding any new resource types to current resources, removing any resource types from current resources, setting whole queue current resource to nil etc.

Also send queue resource change events accordingly.

### What type of PR is it?
* [ ] - Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2169

### How should this be tested?
Using unit tests

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by pbacsko — CHANGES_REQUESTED** [review]
Logging related stuff

**Comment by pbacsko** [comment]
Changes seem to affect TestApplicationHistoryTracking. Please fix that test.

**Comment by manirajv06** [comment]
> Changes seem to affect TestApplicationHistoryTracking. Please fix that test.

fixed

**Comment by pbacsko** [comment]
@manirajv06 the codecov warning is still here, could you check? Maybe it's a false alarm.

**Comment by manirajv06** [comment]
> @manirajv06 the codecov warning is still here, could you check? Maybe it's a false alarm.

those lines has been covered by unit tests

**Review by pbacsko — APPROVED** [review]
+1

**Review by zhuqi-lucas — APPROVED** [review]
LGTM

**Pull request closed without merging**
