### PR TITLE
[YUNIKORN-3004] Lock User Trackers and Group Trackers map during dele…

### PR DESCRIPTION
**Pull request by manirajv06**
…te operations

### What is this PR for?
Lock `userTrackers` and `groupTrackers` map during delete operations.

### What type of PR is it?
* [ ] - Bug Fix

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-3004

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by pbacsko — COMMENTED** [review]
Please also take a look at `resetGroupEarlierUsage()` and `resetGroupEarlierUsage()`. No locks there either and those are called during config refresh I believe. If that's the case, then lock/unlock pair must be added there too.

**Comment by manirajv06** [comment]
> Please also take a look at `resetGroupEarlierUsage()` and `resetGroupEarlierUsage()`. No locks there either and those are called during config refresh I believe. If that's the case, then lock/unlock pair must be added there too.

I did already checked. `resetGroupEarlierUsage()` is called from `clearEarlierSetLimits` which locks the object before calling the earlier.

**Review by pbacsko — APPROVED** [review]

**Comment by wilfred-s** [comment]
We should have a test case for the empty group tracker removal after decrease, requesting a follow up jira

Besides that fix itself is good, all access is now locked.

**Comment by ryankert01** [comment]
Interest in helping create this test! 
jira link: https://issues.apache.org/jira/browse/YUNIKORN-3005

---

@wilfred-s I saw something interesting while trying to create the test: we don't have logic to decrease `qt.maxRunningApps` and `qt.maxResources` while [decreaseTrackedResource() on L159](https://github.com/apache/yunikorn-core/blob/master/pkg/scheduler/ugm/manager.go#L159) requires [it](https://github.com/apache/yunikorn-core/blob/master/pkg/scheduler/ugm/queue_tracker.go#L175) to be zero to be deleted. 
Therefore, in [decreaseTrackedResource() on L183](https://github.com/apache/yunikorn-core/blob/master/pkg/scheduler/ugm/manager.go#L183), it will not be deleted.
Maybe we should relax/add some logic with `qt.maxRunningApps` and `qt.maxResources` ?

**Comment by chenyulin0719** [comment]
@ryankert01 I don't think we need to add other test-only functions for the test case. 

The `maxRunningApps` and `maxResources` in QueueTracker are created from queue configurations and will not be changed during their lifetime.  You should be able to create QueueTracker  with nil `maxRunningApps`/`maxResources`  by configureing the corresponding queue config.

**Comment by ryankert01** [comment]
@chenyulin0719 Great insight! I completely think in the wrong direction (: 
PR submitted!

**Pull request closed without merging**
