### PR TITLE
[YUNIKORN-1122]Move constants to scheduler interface

### PR DESCRIPTION
**Pull request by HuangTing-Yao**
### What is this PR for?
leverage constants from si repo

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-1122

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by HuangTing-Yao** [comment]
Don't know why the lint check failed in `resources/resources_test.go` import.
@pbacsko Could you kindly help to check this error? I can't find any error according the error message.
Thanks.

**Comment by pbacsko** [comment]
@HuangTing-Yao yes, it was a missing new line.

But now there are merge conflicts, please rebase it with the master properly, thanks.

**Comment by HuangTing-Yao** [comment]
Already fix the conflicts, Thanks @pbacsko .

**Review by pbacsko — APPROVED** [review]
+1 LGTM

Will merge it shortly.

**Pull request closed without merging**
