### PR TITLE
[YUNIKORN-2495] Remove Starting application state

### PR DESCRIPTION
**Pull request by craigcondit**
### What is this PR for?
Remove the obsolete Starting state from the Application state machine.

### What type of PR is it?
* [ ] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [x] - Task

### What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-2495

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by wilfred-s — APPROVED** [review]
LGTM, would like some more eyes on this making sure we handle max applications etc correctly

**Comment by wilfred-s** [comment]
Added @lixmgl to the review list for max application impact.

**Review by pbacsko — APPROVED** [review]
+1 LGTM

**Review by chia7712 — APPROVED** [review]
LGTM

**Pull request closed without merging**
