### PR TITLE
[YUNIKORN-2895] Don't add duplicated allocation to node when the allo…

### PR DESCRIPTION
**Pull request by zhuqi-lucas**
…cation already allocated before.

When i try to revisit the new update allocation logic, the potential duplicated allocation to node will happen if the allocation already allocated.  And we try to add the allocation to the node again and don't revert it.

**Note:**

We have unwind logic for another side call for placeholder allocate:

https://github.com/apache/yunikorn-core/blob/fe067b770c25c238449e0b429da92400da8556a4/pkg/scheduler/objects/application.go#L1285

### What type of PR is it?
* [x] - Bug Fix
* [ ] - Improvement
* [ ] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-2895
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Review by craigcondit — CHANGES_REQUESTED** [review]
This will break horribly. If allocateAsk() fails, there is nothing to unwind as the allocation result won't be returned and the final allocation will it happen. Your logic will remove something that was not added in the first place.

**Comment by zhuqi-lucas** [comment]
Thanks @craigcondit for review:
We have inconsistent logic for allocate failed, here is the call with unwind, so i am assuming it may wrong:
https://github.com/apache/yunikorn-core/blob/fe067b770c25c238449e0b429da92400da8556a4/pkg/scheduler/objects/application.go#L1285


It seems both two cases call TryNodeAllocation, so i am confused.

**Comment by wilfred-s** [comment]
-1 on this approach. I think the issue is way more basic. I opened a discussion on the jira as I see multiple issues in the way now track allocations and asks.

**Comment by zhuqi-lucas** [comment]
Thanks @wilfred-s @craigcondit , i will try do add unit test and check the comments, look into the root cause of those issues.

**Comment by craigcondit** [comment]
The `allocateAsk()` call can only fail if the ask was previously allocated. This is checked for in all code paths that call `allocateAsk()` earlier, and always with the application lock held. Therefore, if we ever hit the error case here, we have a serious BUG elsewhere.

**Comment by craigcondit** [comment]
Closing this after determining that original issue is not a problem.

**Pull request closed without merging**
