### PR TITLE
[YUNIKORN-1607] Configuration processing should support limit hierarchical quota check.  

### PR DESCRIPTION
**Pull request by zhuqi-lucas**
### What is this PR for?
A few sentences describing the overall goals of the pull request's commits.
First time? Check out the contributing guide - http://yunikorn.apache.org/community/how_to_contribute   

### What type of PR is it?
* [ ] - Bug Fix
* [x] - Improvement
* [x] - Feature
* [ ] - Documentation
* [ ] - Hot Fix
* [ ] - Refactoring

### Todos
* [ ] - Task

### What is the Jira issue?
* Open an issue on Jira https://issues.apache.org/jira/browse/YUNIKORN-1607
* Put link here, and add [YUNIKORN-*Jira number*] in PR title, eg. `[YUNIKORN-2] Gang scheduling interface parameters`

### Questions:
* [ ] - The licenses files need update.
* [ ] - There is breaking changes for older versions.
* [ ] - It needs documentation.

### CODE REVIEW

**Comment by manirajv06** [comment]
@zhuqi-lucas Created a new pr https://github.com/apache/yunikorn-core/pull/538 for the following reasons:

1. Simplified whole logic for ease of reasoning.
2. New method code flow is in line with existing methods like checkQueueMaxApps & checkQueueMaxResources. Hence it is more easier for us to understand and make changes going forward.
3. In case of empty or nil or lower limit settings at any child Queue level with respect to the Parent Queue limit settings, minimum of both settings should be used to do checks down the level. Please refer the usage of resources.ComponentWiseMinPermissive() method.

Please take a look and share your reviews.

@wilfred-s can you take a look?

**Comment by zhuqi-lucas** [comment]
Sure @manirajv06 , i will review your new PR.

**Comment by pbacsko** [comment]
@zhuqi-lucas can we close this one?

**Comment by zhuqi-lucas** [comment]
Sure, close it now @pbacsko

**Pull request closed without merging**
